// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Dashboard (index.php) AMD module.
 *
 * Exposes global helpers (openLTProfile, closeLTModal, ltSortTable,
 * ltFilterTable, ltToggleAll, ltCountSelected, ltBulkAction) that are
 * called from inline HTML attributes generated by the PHP render functions.
 *
 * @module     local_learnpath/dashboard
 * @copyright  2025 Michael Adeniran
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
define([], function() {
    'use strict';

    // ── Profile modal ─────────────────────────────────────────────────────────

    function openLTProfile(uid, gid) {
        var modal = document.getElementById('lt-modal');
        var frame = document.getElementById('lt-modal-frame');
        if (!modal || !frame) {
            return;
        }
        frame.src = M.cfg.wwwroot + '/local/learnpath/profile.php?userid=' + uid + '&groupid=' + gid;
        modal.classList.add('visible');
        document.body.style.overflow = 'hidden';
    }

    function closeLTModal() {
        var modal = document.getElementById('lt-modal');
        var frame = document.getElementById('lt-modal-frame');
        if (!modal || !frame) {
            return;
        }
        modal.classList.remove('visible');
        frame.src = '';
        document.body.style.overflow = '';
    }

    // ── Client-side column sort ───────────────────────────────────────────────

    function ltSortTable(tableId, colIdx, thEl) {
        var table = document.getElementById(tableId);
        if (!table) {
            return;
        }
        var tbody = table.tBodies[0];
        var rows  = Array.from(tbody.rows);
        var asc   = thEl.dataset.sortDir !== 'asc';
        thEl.dataset.sortDir = asc ? 'asc' : 'desc';
        table.querySelectorAll('.lt-sort-arrow').forEach(function(a) { a.textContent = '⇅'; });
        thEl.querySelector('.lt-sort-arrow').textContent = asc ? '↑' : '↓';
        rows.sort(function(a, b) {
            var av = a.cells[colIdx] ? a.cells[colIdx].innerText.trim() : '';
            var bv = b.cells[colIdx] ? b.cells[colIdx].innerText.trim() : '';
            var an = parseFloat(av.replace('%', ''));
            var bn = parseFloat(bv.replace('%', ''));
            var cmp = (!isNaN(an) && !isNaN(bn)) ? (an - bn) : av.localeCompare(bv);
            return asc ? cmp : -cmp;
        });
        rows.forEach(function(r) { tbody.appendChild(r); });
    }

    // ── Client-side row filter ────────────────────────────────────────────────

    function ltFilterTable(q) {
        q = (q || '').toLowerCase().trim();
        document.querySelectorAll('#lt-summary-table .lt-learner-row').forEach(function(row) {
            var name  = row.getAttribute('data-name')  || '';
            var email = row.getAttribute('data-email') || '';
            row.style.display = (!q || name.includes(q) || email.includes(q)) ? '' : 'none';
        });
    }

    // ── Bulk checkbox helpers ─────────────────────────────────────────────────

    function ltCountSelected() {
        var n  = document.querySelectorAll('.lt-row-check:checked').length;
        var el = document.getElementById('lt-bulk-count');
        if (el) {
            el.textContent = n > 0 ? n + ' selected' : '';
        }
        var sa  = document.getElementById('lt-select-all');
        if (sa) {
            var all = document.querySelectorAll('.lt-row-check').length;
            sa.indeterminate = n > 0 && n < all;
            sa.checked = n === all && all > 0;
        }
    }

    function ltToggleAll(checked) {
        document.querySelectorAll('.lt-row-check').forEach(function(cb) {
            if (cb.closest('tr').style.display !== 'none') {
                cb.checked = checked;
            }
        });
        ltCountSelected();
    }

    // ── Bulk action dispatcher ────────────────────────────────────────────────

    function ltBulkAction(action) {
        var ids = [];
        document.querySelectorAll('.lt-row-check:checked').forEach(function(cb) {
            ids.push(cb.value);
        });
        if (ids.length === 0) {
            window.alert('Please select at least one learner.');
            return;
        }
        var params = new URLSearchParams(window.location.search);
        var gid = params.get('groupid') || '0';

        if (action === 'remind') {
            if (!window.confirm('Send a reminder to ' + ids.length + ' learner(s)?')) {
                return;
            }
            submitHiddenForm(M.cfg.wwwroot + '/local/learnpath/reminders.php', {
                groupid: gid, action: 'bulk_remind', userids: ids.join(','), sesskey: M.cfg.sesskey
            });
        } else if (action === 'enroll') {
            if (!window.confirm('Enrol ' + ids.length + ' selected learner(s) in all missing courses?')) {
                return;
            }
            submitHiddenForm(M.cfg.wwwroot + '/local/learnpath/index.php', {
                groupid: gid, view: 'summary', bulk_enroll: 1, sesskey: M.cfg.sesskey, userids: ids.join(',')
            });
        }
    }

    function submitHiddenForm(action, fields) {
        var form = document.createElement('form');
        form.method = 'post';
        form.action = action;
        Object.keys(fields).forEach(function(k) {
            var fi = document.createElement('input');
            fi.type  = 'hidden';
            fi.name  = k;
            fi.value = fields[k];
            form.appendChild(fi);
        });
        document.body.appendChild(form);
        form.submit();
    }

    // ── Keyboard / overlay close ──────────────────────────────────────────────

    function initModalClose() {
        document.addEventListener('keydown', function(e) {
            if (e.key === 'Escape') {
                closeLTModal();
            }
        });
        var overlay = document.getElementById('lt-modal');
        if (overlay) {
            overlay.addEventListener('click', function(e) {
                if (e.target === overlay) {
                    closeLTModal();
                }
            });
        }
    }

    // ── Search input wiring ───────────────────────────────────────────────────

    function initSearch() {
        var input = document.getElementById('lt-search-input');
        if (input) {
            input.addEventListener('input', function() {
                ltFilterTable(input.value);
            });
        }
    }

    // ── Public API — expose globals for inline onclick attributes ─────────────

    return {
        init: function() {
            // Expose as window globals so existing onclick= attributes keep working
            window.openLTProfile  = openLTProfile;
            window.closeLTModal   = closeLTModal;
            window.ltSortTable    = ltSortTable;
            window.ltFilterTable  = ltFilterTable;
            window.ltToggleAll    = ltToggleAll;
            window.ltCountSelected = ltCountSelected;
            window.ltBulkAction   = ltBulkAction;

            initModalClose();
            initSearch();
        }
    };
});
